INSERT INTO units (name, description, price, hours, performance, measurement_unit) VALUES('LEVANTADO DE RODAPIE DE MADERA', 'Crear rodapie madera', 1.25, 0.0, 40.0, 2);
INSERT INTO units (name, description, price, hours, performance, measurement_unit) VALUES('LEVANTADO DE TARIMA LAMINADA FLOTANTE', 'Crear tarima laminada flotante', 3.00, 0.0, 16.50, 2);
INSERT INTO units (name, description, price, hours, performance, measurement_unit) VALUES('LEVANTADO DE TARIMA DE MADERA FLOTANTE', 'Crear tarima madera flotante', 5.00, 0.0, 10.0, 2);
INSERT INTO units (name, description, price, hours, performance, measurement_unit) VALUES('LEVANTADO DE TARIMA DE MADERA ENCOLADO', 'Crear rodapie madera', 10.00, 0.0, 5.0, 2);
INSERT INTO units (name, description, price, hours, performance, measurement_unit) VALUES('LEVANTADO DE TARIMA DE MADERA SOBRE RASTRELES', 'Crear rodapie madera', 6.0, 0.0, 8.0, 2);
INSERT INTO units (name, description, price, hours, performance, measurement_unit) VALUES('DEMOLICION DE CAPA DE COMPRESION','',12.00,0.0,5.00,1);
INSERT INTO units (name, description, price, hours, performance, measurement_unit) VALUES('LEVANTADO DE MOLDURA DE ESCAYOLA EN TECHO','',3.50,0.0,14.00,2);
INSERT INTO units (name, description, price, hours, performance, measurement_unit) VALUES('DEMOLION DE FALSO TECHO PLADUR O ESCAYOLA','',5.00,0.0,10.00,2);
INSERT INTO units (name, description, price, hours, performance, measurement_unit) VALUES('LEVANTADO DE PAPEL PINTADO','',5.00,0.0,10.00,2);
INSERT INTO units (name, description, price, hours, performance, measurement_unit) VALUES('PICADO DE YESOS Y GUARNECIDOS','',10.00,0.0,5.00,4);
INSERT INTO units (name, description, price, hours, performance, measurement_unit) VALUES('LEVANTADO DE PUERTA DE PASO','',8.50,0.0,6.00,2);
INSERT INTO units (name, description, price, hours, performance, measurement_unit) VALUES('LEVANTADO DE CARPINTERIA DE FACHADA','',9.75,0.0,5.00,2);
INSERT INTO units (name, description, price, hours, performance, measurement_unit) VALUES('LEVANTADO DE ARMARIO EMPOTRADO','',50.00,0.0,1.00,4);
INSERT INTO units (name, description, price, hours, performance, measurement_unit) VALUES('LEVANTADO DE BALDAS O ESTANTERIAS','',11.00,0.0,4.00,4);
INSERT INTO units (name, description, price, hours, performance, measurement_unit) VALUES('DESMONTAJE DE RADIADOR CON REUTILIZACION','',14.00,0.0,4.00,4);
INSERT INTO units (name, description, price, hours, performance, measurement_unit) VALUES('DESMONTAJE DE RADIADOR SIN REUTILIZACION','',10.00,0.0,5.00,4);
INSERT INTO units (name, description, price, hours, performance, measurement_unit) VALUES('DESMONTAJE DE SPLIT AA SIN REUTILIZACION','',25.00,0.0,2.00,4);
INSERT INTO units (name, description, price, hours, performance, measurement_unit) VALUES('DESMONTAJE DE SPLIT AA CON REUTILIZACION','',50.00,0.0,1.00,4);
INSERT INTO units (name, description, price, hours, performance, measurement_unit) VALUES('DESMONTAJE DE MAQ EXTERIOR AA SIN REUTILIZACION','',50.00,0.0,1.00,4);
INSERT INTO units (name, description, price, hours, performance, measurement_unit) VALUES('LEVANTADO DE REJILLAS DE VENTILACION/CLIMATIZACION','',6.00,0.0,8.00,4);
INSERT INTO units (name, description, price, hours, performance, measurement_unit) VALUES('CARGA Y TRANSPORTE DE RESTOS A SACA O CONTENEDOR DE ESCOMBROS EN VIA PUBLICA','',40.00,0.0,0.25,3);
INSERT INTO units (name, description, price, hours, performance, measurement_unit) VALUES('SUMINISTRO Y RETIRADA DE CONTENEDOR DE ESCOMBROS (5 M3)','',10.00,0.0,0.0,4);
INSERT INTO units (name, description, price, hours, performance, measurement_unit) VALUES('SUMINISTRO Y RETIRADA DE SACA  DE ESCOMBROS (1 M3)','',1.00,0.0,0.0,4);
INSERT INTO units (name, description, price, hours, performance, measurement_unit) VALUES('DESMONTAJE DE INSTALACION ELECTRICA','',25.00,0.0,2.00,4);
INSERT INTO units (name, description, price, hours, performance, measurement_unit) VALUES('DESMONTAJE DE INSTALACION TV','',12.00,0.0,4.00,4);
INSERT INTO units (name, description, price, hours, performance, measurement_unit) VALUES('DESMONTAJE DE INSTALACION TELECO','',12.00,0.0,4.00,4);
INSERT INTO units (name, description, price, hours, performance, measurement_unit) VALUES('DESMONTAJE DE INSTALACION CALEFACCION','',25.00,0.0,2.00,4);
INSERT INTO units (name, description, price, hours, performance, measurement_unit) VALUES('DESMONTAJE DE INSTALACION CLIMATIZACION','',25.00,0.0,2.00,4);