------ IMPORT PARA DATABASE ------
INSERT INTO `fabricantes` (`id`,`direccion`,`nombre`,`divisa`,`iva`,`valor`,`referencia`,`telefono`,`url`) VALUES (1,'Juan Jose 23, Madrid','Roca sanitarios S.L','EURO',21.0,60.0,'800','916754344','https://www.roca.es/');
INSERT INTO `fabricantes` (`id`,`direccion`,`nombre`,`divisa`,`iva`,`valor`,`referencia`,`telefono`,`url`) VALUES (2,'Europolis 45 Las Rozas, Madrid','Ikea Las rozas','EURO',21.0,35.0,'801','916566002','https://www.ikea.com/es/es/');
INSERT INTO `fabricantes` (`id`,`direccion`,`nombre`,`divisa`,`iva`,`valor`,`referencia`,`telefono`,`url`) VALUES (3,'Calle del Pico Almenara, 7, 28970 Humanes de Madrid, Madrid','Climatizaciones Frica SL.','EURO',21.0,60.0,'802','910800508','https://frica.es/');
INSERT INTO `fabricantes` (`id`,`direccion`,`nombre`,`divisa`,`iva`,`valor`,`referencia`,`telefono`,`url`) VALUES (4,'Europilis 1 Las Rozas, Madrid','Leroy Merlin Iluminacion','EURO',21.0,35.5,'250','678909876','https://www.leroymerlin.es/iluminacion');
INSERT INTO `fabricantes` (`id`,`direccion`,`nombre`,`divisa`,`iva`,`valor`,`referencia`,`telefono`,`url`) VALUES (5,'C/Cuenca 17 Local3 Leganés','Grupo electrón','EURO',21.0,45.5,'900','918987677','https://www.solucioneselectron.com/instalaciones-electricas-madrid/');
INSERT INTO `fabricantes` (`id`,`direccion`,`nombre`,`divisa`,`iva`,`valor`,`referencia`,`telefono`,`url`) VALUES (6,'Polígono Industrial de Sabón. 15142 Arteixo. A Coruña','Talleres Arteixo','EURO',21.0,28.0,'200','981633006','http://www.talleresarteixo.com/');
INSERT INTO `fabricantes` (`id`,`direccion`,`nombre`,`divisa`,`iva`,`valor`,`referencia`,`telefono`,`url`) VALUES (7,'Av. Rey Juan Carlos I, 8, 28915 Leganés, Madrid','La Pinturería S.L.','EURO',21.0,40.0,'903','916862823','https://centroprocolor.es/');
INSERT INTO `fabricantes` (`id`,`direccion`,`nombre`,`divisa`,`iva`,`valor`,`referencia`,`telefono`,`url`) VALUES (8,'España','Todo puertas','EURO',21.0,50.0,'355','628880094','https://todopuertas.net/');
INSERT INTO `fabricantes` (`id`,`direccion`,`nombre`,`divisa`,`iva`,`valor`,`referencia`,`telefono`,`url`) VALUES (9,'Passatge Posoltega, 5 08030 Barcelona','Ahorra clima','EURO',21.0,35.5,'357','678909876','https://ahorraclima.es/');
INSERT INTO `fabricantes` (`id`,`direccion`,`nombre`,`divisa`,`iva`,`valor`,`referencia`,`telefono`,`url`) VALUES (10,'Barcelona','Bauhaus','EURO',21.0,60.0,'219','931599040','https://www.bauhaus.es/');
INSERT INTO `fabricantes` (`id`,`direccion`,`nombre`,`divisa`,`iva`,`valor`,`referencia`,`telefono`,`url`) VALUES (11,'Europolis 4 Las Rozas','Bricodepot','EURO',21.0,42.0,'221','914456677','https://www.bricodepot.es/');
INSERT INTO `fabricantes` (`id`,`direccion`,`nombre`,`divisa`,`iva`,`valor`,`referencia`,`telefono`,`url`) VALUES (12,'C/Loro 34, Madrid','Brico ventana','EURO',21.0,57.0,'169','916778765','http://www.brico-ventana.es/');
INSERT INTO `fabricantes` (`id`,`direccion`,`nombre`,`divisa`,`iva`,`valor`,`referencia`,`telefono`,`url`) VALUES (14,'C/Amado 34, Aranjuez','Fabricante de Solados','EURO',21.0,28.5,'134','678909876','');
INSERT INTO `fabricantes` (`id`,`direccion`,`nombre`,`divisa`,`iva`,`valor`,`referencia`,`telefono`,`url`) VALUES (15,'C/ Castellana 25','Fabricante de Techos','EURO',21.0,21.5,'886','678909876','');
