INSERT INTO `fabricantes` (`id`,`direccion`,`nombre`,`divisa`,`iva`,`valor`,`referencia`,`telefono`,`url`) VALUES (1,'sadasdadasda','Prueba','EURO',1.3,2,'100','678909876','');
INSERT INTO `fabricantes` (`id`,`direccion`,`nombre`,`divisa`,`iva`,`valor`,`referencia`,`telefono`,`url`) VALUES (2,'kjksfjhksjfhkjsh','Instalador de bañeras','EURO',1.3,30,'800','678909876','');
INSERT INTO `fabricantes` (`id`,`direccion`,`nombre`,`divisa`,`iva`,`valor`,`referencia`,`telefono`,`url`) VALUES (3,'kjksfjhksjfhkjsh','Instalador de inodoros','EURO',1.3,25,'801','678909876','');
INSERT INTO `fabricantes` (`id`,`direccion`,`nombre`,`divisa`,`iva`,`valor`,`referencia`,`telefono`,`url`) VALUES (4,'sadasdadasda','Fabricante de lavabos','EURO',1.3,44.5,'250','678909876','');
INSERT INTO `fabricantes` (`id`,`direccion`,`nombre`,`divisa`,`iva`,`valor`,`referencia`,`telefono`,`url`) VALUES (5,'kjksfjhksjfhkjsh','Instalador de duchas','EURO',1.3,27.5,'900','678909876','');
INSERT INTO `fabricantes` (`id`,`direccion`,`nombre`,`divisa`,`iva`,`valor`,`referencia`,`telefono`,`url`) VALUES (6,'sadasdadasda','Fabricante de climatizaciones','EURO',1.3,100,'200','678909876','');
INSERT INTO `fabricantes` (`id`,`direccion`,`nombre`,`divisa`,`iva`,`valor`,`referencia`,`telefono`,`url`) VALUES (7,'kjksfjhksjfhkjsh','Instalador de ventanas','EURO',1.3,302.5,'903','678909876','');
INSERT INTO `fabricantes` (`id`,`direccion`,`nombre`,`divisa`,`iva`,`valor`,`referencia`,`telefono`,`url`) VALUES (8,'kjksfjhksjfhkjsh','Instalador de puertas','EURO',1.3,21.3,'355','678909876','');
INSERT INTO `fabricantes` (`id`,`direccion`,`nombre`,`divisa`,`iva`,`valor`,`referencia`,`telefono`,`url`) VALUES (9,'kjksfjhksjfhkjsh','Instalador de radiadores','EURO',1.3,54.3,'357','678909876','');
INSERT INTO `fabricantes` (`id`,`direccion`,`nombre`,`divisa`,`iva`,`valor`,`referencia`,`telefono`,`url`) VALUES (10,'sadasdadasda','Fabricante de Mobiliario Obra','EURO',1.3,150,'219','678909876','');
INSERT INTO `fabricantes` (`id`,`direccion`,`nombre`,`divisa`,`iva`,`valor`,`referencia`,`telefono`,`url`) VALUES (11,'sadasdadasda','Fabricante de Pintura','EURO',1.3,50,'221','678909876','');
INSERT INTO `fabricantes` (`id`,`direccion`,`nombre`,`divisa`,`iva`,`valor`,`referencia`,`telefono`,`url`) VALUES (12,'sadasdadasda','Fabricante de Revestimiento','EURO',1.3,30,'169','678909876','');
INSERT INTO `fabricantes` (`id`,`direccion`,`nombre`,`divisa`,`iva`,`valor`,`referencia`,`telefono`,`url`) VALUES (13,'sadasdadasda','Fabricante de Rodapies','EURO',1.3,28.5,'171','678909876','');
INSERT INTO `fabricantes` (`id`,`direccion`,`nombre`,`divisa`,`iva`,`valor`,`referencia`,`telefono`,`url`) VALUES (14,'sadasdadasda','Fabricante de Solados','EURO',1.3,28.5,'134','678909876','');
INSERT INTO `fabricantes` (`id`,`direccion`,`nombre`,`divisa`,`iva`,`valor`,`referencia`,`telefono`,`url`) VALUES (15,'sadasdadasda','Fabricante de Techos','EURO',1.3,28.5,'886','678909876','');
